apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default 8080 }}
{{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
  type: NodePort
{{- end }}
  selector:
    app: {{ .Release.Name }}
