spring:
  application:
    name: user-service
  config:
    import:
      - db.yml
      - ssl.yml
      - security.yml
      - rest.yml

server:
  port: 8080

logging:
  level:
    com.sandwich.app: DEBUG

management:
  metrics:
    distribution:
      slo:
        http.server.requests: 10ms, 50ms, 100ms, 200ms, 300ms, 500s, 800ms
  endpoint:
    metrics:
      access: read_only
    prometheus:
      access: read_only
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  endpoints:
    web.exposure:
      include: '*'
  prometheus:
    metrics:
      export:
        enabled: true


